<a href="https://colab.research.google.com/github/NdanyuzweP/alu-machine_learning/blob/main/Copy_of_Formative_Assignment_PCA_Prince_Ndanyuzwe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



<center>
    <img src="https://miro.medium.com/v2/resize:fit:300/1*mgncZaKaVx9U6OCQu_m8Bg.jpeg">
</center>



The goal of PCA is to extract information while reducing the number of features
from a dataset by identifying which existing features relate to another. The crux of the algorithm is trying to determine the relationship between existing features, called principal components, and then quantifying how relevant these principal components are. The principal components are used to transform the high dimensional data to a lower dimensional data while preserving as much information. For a principal component to be relevant, it needs to capture information about the features. We can determine the relationships between features using covariance.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as eig

In [2]:

data = np.array([
    [   1,   2,  -1,   4,  10],
    [   3,  -3,  -3,  12, -15],
    [   2,   1,  -2,   4,   5],
    [   5,   1,  -5,  10,   5],
    [   2,   3,  -3,   5,  12],
    [   4,   0,  -3,  16,   2],
])

### Step 1: Standardize the Data along the Features

![image.png](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLxe5VYCBsaZddkkTZlCY24Yov4JJD4-ArTA&usqp=CAU)




Explain why we need to handle the data on the same scale.

**[TO DO: Insert Answer here]**

In [3]:
standardized_data = data - np.mean(data, axis=0)
print(standardized_data)

[[ -1.83333333   1.33333333   1.83333333  -4.5          6.83333333]
 [  0.16666667  -3.66666667  -0.16666667   3.5        -18.16666667]
 [ -0.83333333   0.33333333   0.83333333  -4.5          1.83333333]
 [  2.16666667   0.33333333  -2.16666667   1.5          1.83333333]
 [ -0.83333333   2.33333333  -0.16666667  -3.5          8.83333333]
 [  1.16666667  -0.66666667  -0.16666667   7.5         -1.16666667]]


![cov matrix.webp](https://dmitry.ai/uploads/default/original/1X/9bd2851674ebb55e404cc3ff5e2ffe65b42ff460.png)

We use the pair - wise covariance of the different features to determine how they relate to each other. With these covariances, our goal is to group / cluster based on similar patterns. Intuitively, we can relate features if they have similar covariances with other features.

### Step 2: Calculate the Covariance Matrix



In [4]:
cov_matrix = np.cov(standardized_data, rowvar=False)

print(cov_matrix)

[[  2.16666667  -1.06666667  -1.76666667   5.5         -4.36666667]
 [ -1.06666667   4.26666667   0.46666667  -6.6         19.66666667]
 [ -1.76666667   0.46666667   1.76666667  -3.3          2.36666667]
 [  5.5         -6.6         -3.3         24.7        -27.9       ]
 [ -4.36666667  19.66666667   2.36666667 -27.9         92.56666667]]


### Step 3: Eigendecomposition on the Covariance Matrix


In [5]:
eigenvalues, eigenvectors = eig.eig(cov_matrix)
print(eigenvalues, eigenvectors)

[1.07224751e+02 1.61823788e+01 1.93173735e+00 1.27579741e-01
 2.20003762e-04] [[-0.05817655 -0.2631212   0.57237125  0.6292347  -0.45148374]
 [ 0.19774895 -0.03283879  0.06849106 -0.60720902 -0.7657827 ]
 [ 0.0328828   0.17887983 -0.75671562  0.45776292 -0.42983171]
 [-0.33200499 -0.88598416 -0.30234056 -0.11461168  0.01609676]
 [ 0.91989252 -0.33574235 -0.06059523  0.11259736  0.15724145]]


### Step 4: Sort the Principal Components
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

In [6]:
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

order_of_importance = np.argsort(eigenvalues)[::-1]
print ( 'the order of importance is :\n {}'.format(order_of_importance))

# utilize the sort order to sort eigenvalues and eigenvectors
sorted_eigenvalues = eigenvalues[order_of_importance] # sort the eigenvalues

print('\n\n sorted eigen values:\n{}'.format(sorted_eigenvalues))
sorted_eigenvectors = eigenvectors[:,order_of_importance] # sort the eigenvectors
print('\n\n The sorted eigen vector matrix is: \n {}'.format(sorted_eigenvectors))

the order of importance is :
 [0 1 2 3 4]


 sorted eigen values:
[1.07224751e+02 1.61823788e+01 1.93173735e+00 1.27579741e-01
 2.20003762e-04]


 The sorted eigen vector matrix is: 
 [[-0.05817655 -0.2631212   0.57237125  0.6292347  -0.45148374]
 [ 0.19774895 -0.03283879  0.06849106 -0.60720902 -0.7657827 ]
 [ 0.0328828   0.17887983 -0.75671562  0.45776292 -0.42983171]
 [-0.33200499 -0.88598416 -0.30234056 -0.11461168  0.01609676]
 [ 0.91989252 -0.33574235 -0.06059523  0.11259736  0.15724145]]


Question:

1. Why do we order eigen values and eigen vectors?

[Insert Answer here]

2. Is it true we would consider the lowest eigen value compared to the highest? Defend your answer

[insert answer here]


You want to see what percentage of information each eigen value holds. You would have print out the percentage of each eigen value using the formula



> (sorted eigen values / sum of all sorted eigen values) * 100



In [7]:
# use sorted_eigenvalues to ensure the explained variances correspond to the eigenvectors

#TO DO: Insert code here
explained_variance = (sorted_eigenvalues / np.sum(sorted_eigenvalues)) * 100
explained_variance =["{:.2f}%".format(value) for value in explained_variance]
print( explained_variance)

['85.46%', '12.90%', '1.54%', '0.10%', '0.00%']


#Initialize the number of Principle components then perfrom matrix multiplication with the variable K example k = 3 for 3 priciple components




> The reulting matrix (with reduced data) = standardized data * vector with columns k

See expected output for k = 2



In [8]:
k = 2 # select the number of principal components

reduced_data = sorted_eigenvectors[:, order_of_importance[:k]]
reduced_data = np.matmul(standardized_data, reduced_data)

In [9]:
print(reduced_data)

[[  8.21056207   2.45923952]
 [-18.61365432   3.04511679]
 [  3.32229116   3.72878901]
 [  1.05708322  -2.91311904]
 [  9.79214894   0.24805102]
 [ -3.76843107  -6.5680773 ]]


In [10]:
print(reduced_data.shape)

(6, 2)


# *What are 2 positive effects and 2 negative effects of PCA

Benefits of PCA
Dimensionality Reduction:

Simplifies datasets by reducing the number of features while retaining significant information, improving visualization and analysis, and enhancing machine learning performance.
Noise Reduction:

Filters out noise and irrelevant features, leading to cleaner datasets and more accurate predictive models.
Limitations of PCA
Loss of Interpretability:

Principal components are linear combinations of original features, making the results harder to interpret.
Assumption of Linearity:

Assumes linear relationships, which may not be effective for datasets with complex, nonlinear structures.